
import SocketProvider from "@/context/SocketProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Deploy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SocketProvider>
        {children}
      </SocketProvider>
    </div>
  );
}
