import { ThemeProvider } from "@/providers/theme/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { redirect } from "next/navigation";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {isAuthenticated} = getKindeServerSession();
  if(!await isAuthenticated()){
    redirect("/api/auth/login")
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider disableTransitionOnChange attribute="class" defaultTheme="dark" enableSystem>
          <Nav/>
          {children}
        </ThemeProvider>
        <Toaster/>
      </body>
    </html>
  );
}
